apiVersion: v1
kind: Service
metadata:
  name: flask-load-balancer-service 
spec:
  type: NodePort
  selector:
    app: flask-load-balancer
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082 
