apiVersion: v1
kind: Service
metadata:
  name: backend-service-3  # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: backend-service-3
  ports:
    - port: 8090
      targetPort: 8090
