apiVersion: v1
kind: Service
metadata:
  name: backend-service-2  # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: backend-service-2
  ports:
    - port: 8084
      targetPort: 8084
