apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v3-deployment  # TODO: Add a unique name 
spec:
  replicas: 2  # TODO: Adjust the replica count as desired
  selector:
    matchLabels:
      app: backend-v3-deployment
  template:
    metadata:
      labels:
        app: backend-v3-deployment
    spec:
      containers:
      - name: backend-v3-deployment
        # TODO: Replace <your-dockerhub-username> with your Docker Hub username
        image: sophiezh/abtest-server:v1
        ports:
        - containerPort: 8090
        env:
        - name: MODEL_PORT
          value: "8090"