apiVersion: v1
kind: Service
metadata:
  name: backend-service-1  # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: backend-service-1
  ports:
    - port: 8083
      targetPort: 8083
