FROM python:3.10-slim

WORKDIR /app
COPY . .

RUN apt-get update \
    && apt-get install -y procps git\
    && pip install -r requirements.txt

RUN chmod +x startKafkaFetch.sh
CMD ["./startKafkaFetch.sh"]
